# Generated by Django 6.0.3 on 2026-04-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mobile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("ram", models.IntegerField()),
                ("rom", models.IntegerField()),
                ("battry", models.IntegerField()),
            ],
        ),
    ]
