# Generated by Django 6.0.3 on 2026-04-21 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mobile",
            old_name="battry",
            new_name="battery",
        ),
    ]
