# Generated by Django 6.0.3 on 2026-04-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="event_images/"),
        ),
    ]
