# Generated by Django 6.0.3 on 2026-05-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("teacher", models.CharField(max_length=100)),
                ("no_students", models.IntegerField()),
                ("batch", models.CharField(max_length=10)),
                ("starts_at", models.TimeField()),
                ("ends_at", models.TimeField()),
            ],
        ),
    ]
