# Generated by Django 6.0.3 on 2026-05-02 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ModelClass",
            new_name="Class",
        ),
    ]
