# Generated by Django 6.0.3 on 2026-05-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_modelclass_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="ends_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="class",
            name="starts_at",
            field=models.DateTimeField(),
        ),
    ]
