# Generated by Copilot on 2026-05-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_class_ends_at_alter_class_starts_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="ends_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="class",
            name="starts_at",
            field=models.DateTimeField(),
        ),
    ]
