# Generated by Django 6.0.3 on 2026-04-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctor_name", models.CharField(max_length=100)),
                ("sepcialization", models.CharField(max_length=200)),
                ("year_of_experience", models.IntegerField()),
                ("contect_number", models.IntegerField()),
                (
                    "doctor_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="doctor_profiles/"
                    ),
                ),
            ],
        ),
    ]
