# Generated by Django 6.0.3 on 2026-05-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctor",
            old_name="contect_number",
            new_name="contact_number",
        ),
        migrations.RenameField(
            model_name="doctor",
            old_name="sepcialization",
            new_name="specialization",
        ),
        migrations.AddField(
            model_name="doctor",
            name="slug",
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
