# Generated by Django 6.0.3 on 2026-04-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("sid", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("std", models.IntegerField()),
                ("gender", models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
