# Generated by Django 6.0.3 on 2026-04-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_student_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Emp",
            fields=[
                ("empid", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("dept", models.CharField(max_length=100)),
                ("salary", models.IntegerField()),
            ],
        ),
    ]
