# Generated by Django 6.0.3 on 2026-04-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_emp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emp",
            old_name="salary",
            new_name="deptno",
        ),
        migrations.RenameField(
            model_name="emp",
            old_name="dept",
            new_name="job",
        ),
        migrations.RemoveField(
            model_name="emp",
            name="empid",
        ),
        migrations.AddField(
            model_name="emp",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="emp",
            name="sal",
            field=models.IntegerField(default=0),
        ),
    ]
