# Generated by Django 6.0.3 on 2026-04-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookTables",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=200)),
                ("publisher", models.CharField(max_length=100)),
                ("publication_date", models.DateField()),
                ("price", models.IntegerField()),
            ],
        ),
    ]
