# Generated by Django 6.0.3 on 2026-04-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deptno", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("date_of_join", models.DateField()),
                ("age", models.IntegerField()),
                ("salary", models.IntegerField()),
                ("department", models.CharField(max_length=100)),
            ],
        ),
    ]
