# Generated by Django 6.0.3 on 2026-04-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("rollno", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("std", models.CharField(max_length=10)),
                ("sec", models.CharField(max_length=10)),
                ("gender", models.CharField(max_length=10)),
            ],
        ),
    ]
