# Generated by Django 6.0.3 on 2026-04-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="std",
            field=models.IntegerField(),
        ),
    ]
