# Generated by Django 6.0.3 on 2026-04-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_student_std"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="rollno",
            field=models.IntegerField(),
        ),
    ]
